[build]
  command = "yarn build"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.19.1"
  NODE_OPTIONS="--max_old_space_size=8192"

[build.processing.html]
  pretty_urls = false # https://v2.docusaurus.io/docs/deployment/#deploying-to-netlify

