name: __Stage__Deploy_docusaurus
on:
  workflow_dispatch:
jobs:
  stage_deploy:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      
      - uses: actions/cache@v3
        id: cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          
      
      - uses: actions/checkout@v3
        with:
          repository: starrocks/starrocks
          fetch-depth: 0
          path: ./temp

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
      
      - run: npm run copy
      - name: Build website
        run:  |
          export NODE_OPTIONS="--max_old_space_size=12288"
          export DOCUSAURUS_IGNORE_SSG_WARNINGS=true
          yarn build

